### ISSUE TITLE
Dataset configuration question

### ISSUE THREAD

**Issue by hoya-cho** [zyayoung/Iter-Deformable-DETR#10]
The format of crowdhuman data is known as the odgt format.
Are you using the crowdhuman data format converted to coco format?

and Do I have to input both coco format json(train,eval) and odgt format json(train,eval) into config.py?
If so, how do I convert odgt to other custom data that is not in odgt format?

**Comment by zyayoung** [comment]
The short answer is Yes for both questions.
The coco format is for training and odgt is only for evaluation.
If you want to try on a custom dataset, you can just use the coco json format or rewrite the code for loading your custom dataset.
