### ISSUE TITLE
NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Aliweka2020** [zyayoung/Iter-Deformable-DETR#2]
when running your code on kaggle server this error appears to me 

File "/kaggle/input/iter302/Iter-Deformable-DETR-main/detr/deformable_transformer.py", line 395, in forward
    pred_boxes = self.bbox_embed[lid](output) + inverse_sigmoid(reference_points)
TypeError: 'NoneType' object is not subscriptable

In your code, you initialize  bbox_embed as:
self.bbox_embed = None
 self.class_embed = None

then in the forward pass to try to subscripe it.

when running your code on my own laptop with RTX2060 GPU, this error appears

    assert (input_spatial_shapes[:, 0] * input_spatial_shapes[:, 1]).sum() == Len_in
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

it doesn't work for me

**Comment by zyayoung** [comment]
bbox_embed and class_embed are initialized here:
https://github.com/zyayoung/Iter-Deformable-DETR/blob/0a1f881c8b2b119fc4248f97df9ec80e0921d685/detr/deformable_detr.py#L98-L99

For the illegal memory access issue, you may follow the instruction "for debugging consider passing CUDA_LAUNCH_BLOCKING=1."
You are welcome to post the output if it still doesn't work for you.
