### ISSUE TITLE
Width and height in clip_all_boader are always NONE

### ISSUE THREAD

**Issue by Sundragon1993** [zyayoung/Iter-Deformable-DETR#5]
Thank you so much for your incredible works,

I'm trying to evaluate your code using this command: bash exps/aps_test.sh 49 and encountering this issue, the height and width values don't exist in the "**record**" loaded by the output of testing.py, in specific, the epoch049.human file. As a result, these lines of code will return None:
`
        if "width" in record and self._width is None:
            self._width = record["width"]`
`
        if "height" in record and self._height is None:
            self._height = record["height"]`

And in the clip_all_boarder will face this error:
`assert self._width is not None and self._height is not None`

Do you have any idea to overcome this issue?

**Comment by zyayoung** [comment]
Please refer to issue #1.
