### ISSUE TITLE
Swin-L pretrained backbone is broken

### ISSUE THREAD

**Issue by Sundragon1993** [zyayoung/Iter-Deformable-DETR#6]
Dear author, 

Could you release the pretrained SwinL again?, looks like the uploaded file is broken, I couldn't open it using any zip editor, and as a result, the code isn't working with this backbone ...

**Comment by zyayoung** [comment]
It seems you are right. The uploaded file seems to be truncated. The checkpoint should be 796M in size and
```bash
sha256sum output/model_dump/aps_swinl/checkpoint-49.pth
```
should produce `325c8ba8b822da35bf72698d555f925524c7908a72d9f6daccddd9a7873031c1`.
I'm uploading this file again and will reply and update the link soon.

**Comment by zyayoung** [comment]
The link is updated https://drive.google.com/file/d/11lw3lkIX1jJsqKWOu7vuSIzKtkbfrh3a.

**Comment by Sundragon1993** [comment]
Thank you so much for the prompt reply, we really appreciated it, I'm downloading it!
