### ISSUE TITLE
Inference with a custom image

### ISSUE THREAD

**Issue by Sundragon1993** [zyayoung/Iter-Deformable-DETR#7]
Hi,

Do you have any plan to release the inference code supporting custom images rather than benchmarking with predefined datasets?

**Comment by zyayoung** [comment]
You may modify this function for inference on a single image.
https://github.com/zyayoung/Iter-Deformable-DETR/blob/0a1f881c8b2b119fc4248f97df9ec80e0921d685/testing.py#L137
We don't have an inference code for one single image yet, sorry about that.

**Comment by zyayoung** [comment]
Here is a shorter example for inference.

```python
from glob import glob
import argparse
from PIL import Image

import torch
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
from main import get_args_parser as get_main_args_parser
from detr import build_model
from lib.datasets.coco import make_coco_transforms
from util.misc import nested_tensor_from_tensor_list


def get_inference_arg_parser():
    parser = argparse.ArgumentParser('Inference.')
    parser.add_argument('--pathnames', nargs='*')
    return parser


class GlobDataset(Dataset):
    def __init__(self, pathnames) -> None:
        self.files = []
        for l in map(glob, pathnames):
            self.files.extend(l)
        self.transforms = make_coco_transforms('val')

    def __getitem__(self, index):
        f_path = self.files[index]
        img = Image.open(f_path)
        w, h = img.size
        return self.transforms(img, None)[0], torch.tensor([h, w]), f_path

    def __len__(self):
        return len(self.files)


@torch.no_grad()
def main():
    args, _ = get_inference_arg_parser().parse_known_args()
    print(args)
    main_args = get_main_args_parser().parse_args(_)
    dataset = GlobDataset(args.pathnames)
    model, _, postprocessors = build_model(main_args)
    model.load_state_dict(torch.load(main_args.resume, 'cpu')["model"])
    model.cuda()
    model.eval()
    dataloader = DataLoader(dataset, 1, num_workers=2)
    save_format = '{x1:.1f},{y1:.1f},{w:.1f},{h:.1f},{s:.2f}'
    for samples, orig_sizes, f_paths in tqdm(dataloader):
        samples, orig_sizes = samples.cuda(), orig_sizes.cuda()
        samples = nested_tensor_from_tensor_list(samples)
        outputs = model(samples)
        results = postprocessors['bbox'](outputs, orig_sizes)

        for result, f_path in zip(results, f_paths):
            scores = result['scores']
            boxes = result['boxes']
            keep = scores > 0.05
            for s, b in zip(scores[keep].tolist(), boxes[keep].tolist()):
                x1, y1, x2, y2 = b
                print(save_format.format(x1=x1, y1=y1, w=x2-x1, h=y2-y1, s=s))

if __name__ == '__main__':
    main()
```

**Comment by hoya-cho** [comment]
i have this problem in "model.load_state_dict(torch.load(main_args.resume, 'cpu')["model"])" . how can i solve this problem?

size mismatch for input_proj.0.0.weight: copying a param with shape torch.Size([256, 384, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 512, 1, 1]).
        size mismatch for input_proj.1.0.weight: copying a param with shape torch.Size([256, 768, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 1024, 1, 1]).
        size mismatch for input_proj.2.0.weight: copying a param with shape torch.Size([256, 1536, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 2048, 1, 1]).
        size mismatch for input_proj.3.0.weight: copying a param with shape torch.Size([256, 1536, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 2048, 3, 3]).
